### ISSUE TITLE
Applying MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE when saving document?

### ISSUE THREAD

**Issue by morrowrasmus** [scanny/python-pptx#1021]
I am still very new to using this package, but so far it has proven nice to work with. I have stumbled upon one minor annoyance, and I was wondering if that is something that is purely user error, or if not, whether it is possible to implement this as a feature:  applying the "text to fit shape" property of a text frame immediately when it is saved. Currently, the output .pptx-file will have text that overflows the text shape, and will only resize once I make a modification to the text (for example applying bold to parts of it). This means manual labour to pour through all the slides and making sure there is not overflow.

My use case is to fill an existing shape with text of varying length. My code is written so that it will output at max 12 lines, but the text should always be fit to the shape, so for the cases where I have up to 12 lines, the text should be shrunk relative to the font size in the template. The output .pptx-file does have both "word wrap" and "text to fit shape" enabled, but it has not been applied before I make any adjustment.

```python

from pptx import Presentation
from pptx.enum.text import MSO_AUTO_SIZE

ppt = Presentation('templates/my_template.pptx')

slide = ppt.slides[0]
text_frame = slide.shapes[0].text_frame
text_frame.clear()

description = [
        'This is a list with the text I want to write to the shape.',
        'It can consist of up to twelve lines, and I want the output',
        'to be automatically resized upon overflow.',
        'This example will only have five lines, but placing it in a sufficiently',
        'small shape should still reproduce the issue.'
]

# I have tried placing these at the end as well with no luck.
text_frame.word_wrap = True
text_frame.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE

p = text_frame.paragraphs[0]
p.text = description[0]

for para_str in description[1:]:
    p = text_frame.add_paragraph()
    p.text = para_str
```

**Comment by scanny** [comment]
There is a `TextFrame.fit_text()` method that might be better than nothing, but it's an experimental fixture and unlikely to be improved.

The underlying issue is that fitting text is a rendering-time operation and `python-pptx` is not a renderer. That sort of thing is hard to do in Python, at least it was at the time, involving getting system fonts and their font metrics and then calculating layout and so forth.

Also, fitting text to a shape only works within a narrow range of sizes. Reducing font size doesn't gain as much space as you might think. It doesn't take much more text to drive your point size from 12pt down to 6pt or whatever and that's as far as you can go.

Anyway, might be worth a try but no recourse if it doesn't work for your use case.

**Comment by morrowrasmus** [comment]
Alright, thanks for your quick response. I tried to run `fit_text()`, but that didn't resolve it. I think my best option now would be to write a macro in Powerpoint that automatically applies it for every slide (I just need to toggle bold on and off for it to register, so it should not be too difficult).

This package is in any case helping me avoid a lot of manual labour, so thanks for that.
