### ISSUE TITLE
eps import

### ISSUE THREAD

**Issue by hansvanzwol** [scanny/python-pptx#138]
I am creating plots with matplotlib and would like to import these as vector graphics in powerpoint 2013 (which has high quality postscript import). python-pptx does support emf and wmf images but these backends are not available in matplotlib. Having eps import enabled would be great.

**Comment by scanny** [comment]
@hansvanzwol - This issue came up just yesterday, it turns out that while PowerPoint allows you to insert PDF and EPS images, it converts those to Windows Metafile format (WMF/EMF) before saving them to the .pptx package. So it ends up being insertion of placeable EMF images, which the library already supports.

So I think the challenge here is finding an external way to convert EPS and other PostScript-based formats to (placeable) WMF.

So far I'm not liking the sounds of adding that capability directly in the package because it would require adding a (library) dependency to python-pptx, which is in general a burden to users and a way for incompatibilities to creep in.

But I'm sure folks will be keen to know how to do this for themselves, so if you've worked out a workflow that works for you we'd love for you to share it here so others can do it too :)
