### ISSUE TITLE
Possible bug with auto_shape_type

### ISSUE THREAD

**Issue by joereddington** [scanny/python-pptx#150]
New user so entirely possibly my own fault...  
Iterating over the shapes in a slide, if they are an autoshape I want to find out what type of autoshape they are (rounded corners are special).  The smallest code I have that produces the error is this:

```
#!/usr/bin/python
from pptx import Presentation
prs = Presentation("CommuniKate20-es.pptx")

for slide in prs.slides:
    for shape in slide.shapes:
        if shape.shape_type==1:
            print shape.auto_shape_type
           
```
Running it on this presentation ﻿https://www.dropbox.com/s/2q3m0hpzrxum8mj/CommuniKate20-es.pptx?dl=0  throws this KeyError.  I wondered if that was the expected behaviour? 

```
File "./smallissue.py", line 10, in <module>
    print shape.auto_shape_type
  File "/Library/Python/2.7/site-packages/python_pptx-0.5.7-py2.7.egg/pptx/shapes/autoshape.py", line 301, in auto_shape_type
    return self._sp.prst
  File "/Library/Python/2.7/site-packages/python_pptx-0.5.7-py2.7.egg/pptx/oxml/shapes/autoshape.py", line 179, in prst
    return prstGeom.prst
  File "/Library/Python/2.7/site-packages/python_pptx-0.5.7-py2.7.egg/pptx/oxml/xmlchemy.py", line 232, in get_attr_value
    return self._simple_type.from_xml(attr_str_value)
  File "/Library/Python/2.7/site-packages/python_pptx-0.5.7-py2.7.egg/pptx/enum/base.py", line 189, in from_xml
    return cls._xml_to_member[xml_val]
KeyError: 'foldedCorner'
```

**Comment by scanny** [comment]
Good catch :)

Turns out there is a typo in the enumeration definition for the `FOLDED_CORNER` shape that had that attribute value as 'folderCorner' instead of 'foldedCorner'.

This is fixed and pushed on the develop branch, will make its way into the next maintenance release.

If you want to patch your current installation in the meantime, it's a one character change on line 333 of `/Library/Python/2.7/site-packages/python_pptx-0.5.7-py2.7.egg/pptx/enum/shapes.py`. Or you could reinstall from the GitHub develop branch, that would work too :)

Btw, probably best to use the enumeration for `shape.shape_type` rather than its current int value. Technically those are subject to change (although they've been carefully chosen to match the MS API values), but more importantly perhaps it makes the code more readable.

```python
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE

prs = Presentation("CommuniKate20-es.pptx")

for slide in prs.slides:
    for shape in slide.shapes:
        if shape.shape_type == MSO_SHAPE_TYPE.AUTO_SHAPE:
            print shape.auto_shape_type
```

Thanks for reporting this :)

**Comment by joereddington** [comment]
Fixed. Thank you :) Excellent support. (and awesome project...)
