### ISSUE TITLE
Edit Table and Keep the current format

### ISSUE THREAD

**Issue by janscas** [scanny/python-pptx#228]
Hi, I have a presentation with some table already formatted with font, color, etc...

I need to open the presentation and edit some values of the table and then save it as another presentation.

When doing this, I encounter the fact that each time I edit the property text (or even the paragraph text) the format is set to a new one. The color, font, font size, of the text is lost.

How can I preserve the format of the texts in the table cells?

thanks

**Comment by scanny** [comment]
You need to go down to the run level and make your text changes there. All character formatting is stored as properties of a run. When you assign to Cell.text you replace all the existing runs with a single new one; that's why your formatting is no longer there after.

This can be tricky because PowerPoint has a habit of making a lot of runs for various reasons.

A place to start might be:

```python
for paragraph in cell.text_frame.paragraphs:
    for run in paragraph:
        print run.text
```

This will give you an idea what you're up against. You could also inspect the XML. If you have control over the original document (like it's a template) you can purposely make the content occupy a single run to make life easier.

**Comment by janscas** [comment]
Wow, Some ppt`s have a lot of runs...

Thanks! that was the way to go.

**Comment by scanny** [comment]
Glad you got it working :)
