### ISSUE TITLE
support for pyplot eps images

### ISSUE THREAD

**Issue by adriannye** [scanny/python-pptx#247]
Powerpoint accepts EPS images and there are existing libraries for creating EPS barcharts and piecharts that are way more flexible than the ones in pptx, such as pyplot.    It would be nice to document how to incorporate these images.

**Comment by scanny** [comment]
The PowerPoint UI allows you to insert an EPS (or PDF) image, but what it actually does when you press the 'Ok' button is convert that image to WMF/EMF (Windows "proprietary-ish" vector format) and embed that.

`python-pptx` already has the ability to add WMF images. So what you really need for this is a way to convert EPS images into WMF format.

Last time I looked there were a couple possible options, but that's the route that's going to make sense. If PIL/Pillow started offering this feature we'd certainly want to include a convenient wrapper for it. But until then you'll need to get them into WMF first and insert that.

It would be far from the main focus of `python-pptx` to include specialized code to convert EPS to WMF and that code would be better located on a graphics library project anyway since it would be general purpose. So we're not likely to be writing one of those anytime soon as part of this project :)

**Comment by adriannye** [comment]
Closing this since no code change is needed.
