### ISSUE TITLE
font attributes not being applied?

### ISSUE THREAD

**Issue by gsd4me** [scanny/python-pptx#258]
During development of a project, I am creating slides using text read from an input file. However certain attributes of the slide fonts are (seemingly) not being applied. I have read the fantastic documentation on the package but cannot fathom what I am doing wrongly. I am developing my package on a Windows 10 machine (64 bit), using Pycharm as the IDE, with Python 2.7.  I have "pip"-d pptx to be the latest version and all the dependencies are up to date (lxml, Pillow, et al)

May I ask or your opinion as to what I am doing wrongly here? Attached is a stripped down version of the code, showing only the relevant areas that would interest you, and the full code works perfectly except the setting of the font attributes specified. I have examined the pptx XML file generated by the software and I can confirm that the font never changes from  Calibri, 18-point (which is the default used in the examples in the 
[ppTest.txt](https://github.com/scanny/python-pptx/files/769201/ppTest.txt)

documentation - coincidence?).

**Comment by scanny** [comment]
@gsd4me When I said as simple as possible, I was thinking something more like this:

```python
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE
from pptx.util import Inches


prs = Presentation()
slide = prs.slides.add_slide(prs.slide_layouts[5])
shape = slide.add_shape(
    MSO_SHAPE.ROUNDED_RECTANGLE, Inches(1), Inches(1), Inches(1), Inches(1)
)
paragraph = shape.text_frame.paragraphs[0]
run = paragraph.add_run()
run.text = 'foobar'
prs.save('adb.pptx')
```

You need to do more work on your side to narrow down where the problem is. Get rid of all the loops and conditionals for a start. As near as I can tell, your code is exiting before it ever calls the statements you say aren't working.

You might add some print statements on your side just to make sure you're actually getting to the code you expect you are.
