### ISSUE TITLE
Deleting placeholders

### ISSUE THREAD

**Issue by mariuskueng** [scanny/python-pptx#265]
Given from the documentation (https://python-pptx.readthedocs.io/en/latest/user/placeholders-understanding.html#unpopulated-vs-populated) it should be possible to delete unpopulated placeholders. I was able to identify some unpopulated placeholders but I can't figure out how to actually delete them. 

For example I would like to delete this one: `shapes.placeholders[17]`.
What am I missing?

**Comment by scanny** [comment]
There's no support for this in the API yet. It turns out to be tricky in the general case, because the placeholder shape can be linked to other things like pictures and charts.

But if you know for sure it's empty, than something like what is described here should get it done:
http://stackoverflow.com/questions/39603318/how-to-delete-unpopulated-placeholder-items-using-python-pptx

**Comment by mariuskueng** [comment]
Thanks for the suggestion. It worked as expected.
By the way I also found your answer on StackOverflow but initially only searched on Github. Sorry for extra question. 😆
