### ISSUE TITLE
auto size problem

### ISSUE THREAD

**Issue by mbodziak** [scanny/python-pptx#291]
I have a problem with auto-sizing of text box. The following code does not make any change to the size of text box:

`from pptx import Presentation`
`from pptx.enum.shapes import MSO_SHAPE`
`from pptx.util import Inches, Pt, Cm`
`from pptx.dml.color import RGBColor`
`from pptx.enum.text import PP_ALIGN, MSO_AUTO_SIZE`

`prs = Presentation()`
`slide_layout = prs.slide_layouts[6]`
`slide = prs.slides.add_slide(slide_layout)`
`shapes = slide.shapes`
`left = Cm(10)`
`top = Cm(5)`
`width = Cm(3)`
`height = Cm(0.5)`
`shape = shapes.add_textbox(left, top, width, height)`
`fill = shape.fill`
`fill.solid()`
`fill.fore_color.rgb = RGBColor.from_string('eff3ff')`
`line = shape.line`
`line.color.rgb = RGBColor.from_string('08519c')`
`line.width = Pt(0.25)`
`text_frame = shape.text_frame`
`text_frame.clear()`
`text_frame.word_wrap = True`
`text_frame.auto_size = MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT`
`par = text_frame.paragraphs[0]`
`par.alignment = PP_ALIGN.CENTER`
`par.text = 'Lorem ipsum malorem'`
`prs.save(fname)`

The text box remains with the size defined at the beginning (3 x 0.5 cm).

Best regards,
Marcin

**Comment by scanny** [comment]
This is the expected behavior. If you edit the text box with PowerPoint, or perhaps even just click in it, PowerPoint will adjust its size. But unfortunately, PowerPoint doesn't pro-actively adjust shapes in this way when the file is loaded. I believe LibreOffice *does* make that automatic adjustment.

**Comment by buzzm** [comment]
+1 on the expected behavior.   I had to write a simple (and incomplete) text+font to width function to manually size the font.   Basically   while(1) { ok = fit(text,font,size); if(fit != OK) { size--} else {break;}}

**Comment by scanny** [comment]
Note there is an experimental feature `TextFrame.fit_text()` in `pptx.text.text` that makes best efforts to do the *reverse* of this, that is, adjust text size to fit shape rather than shape size to fit text. It might give an idea of the challenges involved. It's quite a difficult task, actually something that requires a PowerPoint renderer (or part of it anyway) which is beyond the scope of `python-pptx`. It's problematic to do even this bit in Python because it requires access to font metrics, which is platform dependent and for whatever reason isn't available from a robust Python library (or at least wasn't when I last looked).
