### ISSUE TITLE
Images all flipped

### ISSUE THREAD

**Issue by DanielVZ96** [scanny/python-pptx#306]
I'm using python-pptx to automate some presentations I have to make, the problem is that all the images I insert are, in the case of horizontal ones, upside down or, in the case of vertical ones, rotated counter-clockwise. I'm not sure what's going on.

This is the code I'm using to create a new slide for each new image in the folder selected:

```python
for file in listdir():
    try:
        filename, extension = file.split(".")
    except:
        folders_in_path.append(file)
        print("{} is a folder and will be iterated over later.".format(file))
        continue
    if extension in supported_exts:
        print("I made a new image slide!")
        file_slide = new_ppt.slides.add_slide(picture_slide_layout)
        placeholder = file_slide.placeholders[1]
        new_img = placeholder.insert_picture(file)
```

**Comment by DanielVZ96** [comment]
I'm not sure how to insert code in github yet, I'm still new at programming (2 months). Sorry for the mess.

**Comment by scanny** [comment]
I've updated your message to demonstrate; click the edit "pencil" on that message to see the syntax.

I suspect this is a characteristic of the particular images you're inserting.

Have you tried inserting them manually with PowerPoint into picture placeholders and see what happens then?

It definitely doesn't do this with all images and it doesn't try to rotate images, it just plops them in there.

**Comment by DanielVZ96** [comment]
Wow, that's strange. I guess there's a problem with my powerpoint then. The problem is that my office license just expired so I can't edit any presentation 😢 

Thanks for fixing my mess (I'm still new at GitHub and programming) :)

**Comment by scanny** [comment]
I'm not sure if you understand what I'm saying.

The likely cause I expect is that there is a rotation parameter somewhere in the image file that PowerPoint (or LibreOffice it sounds like) is not recognizing. This could happen if the image was, say, shot with a camera held "side-ways" to take a portrait-orientation picture rather than the default landscape orientation. The resulting picture would come out looking rotated 90-degrees right or left, depending on which direction the camera was rotated.

Once downloaded to a computer, it may have had "rotate-left" or "rotate-right" applied by some photo software, which may not completely rewrite the file, just change the orientation or rotation parameter in the file header.

Anyway, to diagnose this you would want to check the image with a photo package and make sure it has the orientation you want, then try inserting it manually into PowerPoint and see if it retains or loses that orientation. If it retains the orientation, that means there is some XML somewhere that's not getting written the way it should and we would want to diagnose that.

But you'll need to rule out other causes first as this is the first issue we've seen on this and that feature has been in the package for years.

**Comment by DanielVZ96** [comment]
Ok. I also thought there could be a problem with the images. They were take with a phone, sideways and straight up, so there may be something there. Also, even though in the mail I received them the photos were rotated, windows put them automatically in the correct orientation, so maybe there may be where the problems lie. I'll check out how the pictures behave in other programs, how other pictures get inserted in the pptx and if there's any difference between PowerPoint and libre office. From then I'll check other stuff out. Thanks for the clarification.

**Comment by DanielVZ96** [comment]
I checked and the problems are tied to the images. Idk why but it looks like the images get inserted in the same orientation the phone was at the moment of the capture. I don't know how to fix this with the photos, but at least your code doesn't have anything wrong. Do you have any idea I could fix this? There are a ton of these images that I need to make a presentation with.

**Comment by scanny** [comment]
Have a search on 'auto rotate phone images'. There's some good information out there on how to do this.
