### ISSUE TITLE
Inserting Non-standard Objects

### ISSUE THREAD

**Issue by ProIngenieur** [scanny/python-pptx#317]
Hi scanny,

I would like to replicate the “Insert Object > Create from file” function using the pptx module, see image below, how best can I achieve this? For your information, the file is an output from an analysis software (Altair HyperWorks) of type ‘filename.h3d’.

![insert_object](https://user-images.githubusercontent.com/31881659/30314778-bbc16378-9799-11e7-9a4e-35ce6a300ceb.PNG)

Thanks for your help.

**Comment by scanny** [comment]
There's no API support for this at the moment. I'm not sure what this feature actually is, but I expect it's something like inserting an OLE object, which of course would only work on Windows.

New features like this are only added by sponsorships, practically speaking. It's conceivable that it could be added by contribution, but that's quite rare actually and this one looks like a fairly big nut. If you're interested in sponsoring a feature like this let me know and we can discuss it. Otherwise, depending on your operating environment, it might be better to look at the Windows API.

**Comment by scanny** [comment]
Added in v0.6.19 on May 16, 2021.
