### ISSUE TITLE
feature: add support for 26+ series in a chart

### ISSUE THREAD

**Issue by ssi-victoriano-eco** [scanny/python-pptx#328]
I'm having a weird behavior in the PPTX file I generated.
The series data is updated correctly, but when I right-click the chart and select "Edit data", the series  data references are broken and the legend and chart is then incorrect.

Please let me know if this is a duplicate and point me to a solution.

```python
import random

from pptx import Presentation
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE, XL_LEGEND_POSITION
from pptx.util import Inches

prs = Presentation()

slide = prs.slides.add_slide(prs.slide_layouts[5])

chart_data = ChartData()

categories = []
brandsTotal = 34
for i in range(1, brandsTotal):
    categories.append('Category ' + str(i))
    chart_data.add_series('Series ' + str(i), random.sample(range(100), brandsTotal-1))

chart_data.categories = categories

x, y, cx, cy = Inches(0.5), Inches(2), Inches(9), Inches(4.5)
chart = slide.shapes.add_chart(
    XL_CHART_TYPE.LINE, x, y, cx, cy, chart_data
).chart

chart.has_legend = True
chart.legend.include_in_layout = False
chart.legend.position = XL_LEGEND_POSITION.TOP

prs.save('chart-01.pptx')
```

## Before Edit Data:
![image](https://user-images.githubusercontent.com/20445767/32299943-66792da8-bf92-11e7-93eb-317cc7bf466d.png)

## After clicking Edit Data:
![image](https://user-images.githubusercontent.com/20445767/32299975-7cb694e8-bf92-11e7-8d11-59c6458c0ee1.png)

**Comment by scanny** [comment]
I think you're going to need to be more specific. It looks like only some series references are broken, although I can't actually tell from your screenshot.

I would start by trying the same code with 3 series instead of 34, and see if that works. If that also doesn't work, it will be a lot easier to narrow things down. If it *does* work, then see where the work/break boundary is (I'm betting around 32 :) and describe that situation.

You'll probably eventually need to inspect the chart XML, so you might want to work out how to do that. `opc-diag` is a handy tool for that. We'll get to what to look for once you've gotten a little further along.

**Comment by ssi-victoriano-eco** [comment]
Sorry, forgot to include that. The boundary seems to be at 25.  At 26+ the references seems to break. I'll try to inspect the XML using opc-diag and will get back to you.

**Comment by scanny** [comment]
Okay, that gives me a hypothesis then. In Excel, columns 1-26 are named 'A'-'Z'. The 27th column is named 'AA'. I'll bet the addressing algorithm in the chart Xlsx writer isn't sophisticated enough to deal with double-letter columns (who ever heard of a 26-series chart after all :).

The data would be fine until you open up the Excel, because PowerPoint does look in the Excel until that point, referring only to the data "cached" in the chart XML.

Let me take a look and see if I can put my finger on where this is coming from in the code ...

**Comment by scanny** [comment]
Okay, I think this is it:
https://github.com/scanny/python-pptx/blob/master/pptx/chart/xlsx.py#L105

Which would explain the behavior you're seeing.

Just out of curiosity, why the need for so many series?

**Comment by ssi-victoriano-eco** [comment]
Thanks for looking into this. We have a dashboard/reporting site that shows different charts and our clients wants those charts to be exported as PPT native charts and the max series on a couple of charts could reach to more than 25, so I was just anticipating this scenario.

**Comment by scanny** [comment]
Okay, got it. I'll leave this open as a feature request to support 26+ series. If you guys have project budget I can probably add this in a few hours work; most new work on `python-pptx` comes by way of sponsored features.

**Comment by scanny** [comment]
Added support for 26+ chart series in release v0.6.10 on Jun 11, 2018.
