### ISSUE TITLE
Formatting damaged while replacing text

### ISSUE THREAD

**Issue by some** [scanny/python-pptx#335]
Using a well formatted PPT template, I tried to replace a string within all existing components to get a well formatted customized presentation.

The text replacement worked fine, but the **formatting was quite damaged making the PPT unusable for a  presentation**. Is there a way to avoid damaging the formatting while replaceing the text placeholders? 

Here the method I used to do the replacement:

```
for slide in ppt.slides:
    for shape in slide.shapes:
        if shape.has_text_frame:
            shape.text = shape.text.replace(   search_str    ,    repl_str    )
```

**Comment by scanny** [comment]
@some this is really a support question. The behavior you're seeing is the expected behavior. The short version is you need to replace text at the run level if you want to preserve formatting. If you post your question on StackOverflow (using the `python-docx` tag) you can receive a more detailed answer. Make sure to post there a picture of the resulting formatting along with this code you used.
