### ISSUE TITLE
always a blank line using "slide.shapes.add_textbox(...)"

### ISSUE THREAD

**Issue by bobo2cj** [scanny/python-pptx#346]
please comment a line #434
"../python2.7/site-packages/pptx/oxml/shapes/autoshape.py"

            # '    <a:p/>\n'

or add "if ..."

thanks

**Comment by scanny** [comment]
Each shape `text_frame` must contain at least one paragraph. This is a PowerPoint requirement and is consistent with what you get when you create a new shape in the application. Otherwise there would be no place for the insertion point.

I understand this is sometimes inconvenient for use by code, but there's no avoiding it.
