### ISSUE TITLE
Add a image in table cell using python-pptx

### ISSUE THREAD

**Issue by Puneetsofto** [scanny/python-pptx#363]
I am using the python-pptx library to create a table in pptx document. I want to add an image in the table cell, but I haven't found such option to do so.

I am adding cell using following code:

table.cell(0, 1).text = 'cell text'

Please help me how we can add an image in a table cell using python-pptx.

Quick response will be appreciated.

**Comment by scanny** [comment]
Please use StackOverflow for support questions (using the 'python-pptx' tag). The issues list is reserved for feature requests and suspected bugs.

**Comment by Puneetsofto** [comment]
Hi @scanny , I have added this question on stackoverflow. This is the link:
https://stackoverflow.com/questions/49382280/add-a-image-in-table-cell-using-python-pptx

Can you please look into this?

**Comment by YiannisGkoufas** [comment]
Hi @scanny I think that would be an incredibly handy feature. Can you share any pointers about we could implement this functionality?

**Comment by scanny** [comment]
@YiannisGkoufas It looks like the approach that might work would be setting the cell background to be an image. Definitely make this work manually with PowerPoint first before you invest the work. That way you can see any shortcomings, like I expect it's critical to get the cell height correct for it to look good.

Then dump out the XML to see how it works in the XML syntax, something like:

```python
cell = table.cell(0, 0)
print(cell._tc.xml)
```

And then work out how to get that XML into a cell that is as close as you can make it with the `python-pptx` API. This part is what is typically called a "workaround function". These use some combination of `lxml` API calls and `python-pptx` internals to make the desired changes. If you search on `python-pptx workaround function` you'll come across some examples.

Noodling it a bit this is going to be a little tricky because you'll need to add a relationship for each image you use. But maybe dig into it a bit and see how far you can get and ask questions from there.

**Comment by YiannisGkoufas** [comment]
Thanks so much @scanny for the details! will definitely start poking it. For the time being I add images on the page directly and try to compute their dynamic (X,Y) and set the necessary offsets.
Thanks!

**Comment by Inouyasha** [comment]
`
def add_image_in_table_cell(cell, url):
    response = get(url)
    img_bytes = BytesIO(response.content)

    image_part, rId = cell.part.get_or_add_image_part(img_bytes)
    tcPr = cell._tc.get_or_add_tcPr()

    xml = f"""<a:blipFill {nsdecls("a")}> 
                      <a:blip {nsdecls("r")} r:embed="{rId}"/>
                      <a:stretch>
                        <a:fillRect/>
                      </a:stretch>
                    </a:blipFill>"""
    ele = parse_xml(xml)

    tcPr.clear()
    tcPr.append(ele)
`

**Comment by MartinPacker** [comment]
The nice thing about adding pictures to table cells is it makes a way to do multiple pictures on a slide with easier dimension setting than what I do at present: Calculating positions.

Another nice thing is you could have eg bulleted lists in cells next to (or below) pictures.

I'd want to be able to make table and cell borders transparent, though.

The down side comes to when the pictures are different sizes and you'd have to find a way to add padding or accept suboptimal scaling.

If we can find a way to deal with the latter (problem) I'd be all for python-pptx having this capability.

**Comment by scanny** [comment]
This is a closed issue, so if you want to discuss more best to open a new one. This is not adding an image to a table cell per-se, it is setting the background of a cell to be an image. The cell would still be able to contain text and so forth. I expect there are different modes as well like repeat/tile the image, scale/stretch to fill, and put at top-left at full size and leave it at that.

So perhaps an interesting feature, but not adding a picture to a cell per se (which is not strictly possible in PPTX although it is in DOCX).
