### ISSUE TITLE
shape: Querying shape size and position

### ISSUE THREAD

**Issue by jhludwig** [scanny/python-pptx#40]
Request for support to query the position and size of an existing shape (and set them to new values?)

One use is to allow an existing image in presentation to be characterized, so that it can be replaced with an image of the same size and resolution.

Shapes of the following types can appear in Slide.shapes (`<p:spTree>`) and each will require support:
- [x] sp -- Auto Shape
- [x] pic -- Picture
- [ ] grpSp -- Group Shape
- [ ] graphicFrame -- container for table and chart shapes
- [ ] cxnSp -- Connector (line)
- [ ] contentPart -- has no position, but should return None instead of raising an exception

**Comment by rpeys** [comment]
Has support for querying the width and height of a table been implemented? It would be useful to me because I want to position a table on my slide to be in the bottom right corner. If I could know how wide/tall my table is after I fill it with values, I could back-work the appropriate values for "left" and "top" that would place it in the bottom-right corner. Thanks!

For ex, I create a table using: table = shapes.add_table(rows, cols, left, top, width, height).table
Then I loop through the cells and fill each with a different value, and the size of the table will shift to accommodate.
I would like to then query the final width and height of my table, to ultimately reset the left and top attributes.

**Comment by rpeys** [comment]
I am working with a table and would like to query its final height after it has been populated with values. This way I will be able to adjust its position on the slide (graphicframe.top) according to how large it is. I add the table with these lines:
`graphicframe = shapes.add_table(rows = 41, cols = 5, left = Inches(0), top = Inches(2), width = Inches(5.7), height = Inches(4))
table = graphicframe.table`
And then loop through its cells to populate them individually. The table height changes to accommodate the input (for example, text may wrap on to 2 lines, increasing the height).

graphicframe.height returns the original height which I inputted to add_table, and not the final height after data population. 

I found what looks to be the height of each row in the XML file (see image below), but even those correspond to the original height from add_table, not the empirical final height of the table after data population. [89209*40+89240 = Inches(4), my original height assigned to the table]
![image](https://user-images.githubusercontent.com/19732554/28181413-87361952-67d6-11e7-9b41-8bf20c05621e.png)

Do you know how I can find the empirical height of my table after it is populated? Thank you!!

**Comment by scanny** [comment]
@rpeys This is a closed issue and you're asking a new question. This isn't the place for it. Please ask support questions on Stack Overflow using the 'python-pptx' tag.
