### ISSUE TITLE
Feature Request: Save PPTx as video

### ISSUE THREAD

**Issue by kanakiyajay** [scanny/python-pptx#426]
Hi @scanny,

I don't know whether this feature exists or not, but currently a different tool to convert the ppt to a video. 

From [this line](https://github.com/stakach/powerpoint-to-video/blob/master/PPTVideo/Program.cs#L33), it does not appear difficult to do so.

**Comment by scanny** [comment]
This is outside the scope of python-pptx. Feel free to use that tool if you have this requirement.

**Comment by ishandutta2007** [comment]
I was under the impression `pptx.Presentation.save()` does save as video as well.
@scanny Can you explain why it is outside the scope. My feeling is any button that exists in ms powerpoint should be an api here ?

**Comment by scanny** [comment]
The PowerPoint application is at least two things, a PPTX file editor (CRUD) and a presentation _renderer_.

`python-pptx` is only the former. In addition, it is a partial implementation, something like 50% of the feature set, like an 80/20 implementation bumped up to 98/50. (the 50% of the features folks need 98% of the time).

Video export, saving as PDF, reducing text to fit, exporting slides as images, etc., etc. are rendering tasks and so out of this project's scope.

Btw, Python wouldn't be the right choice for a rendering engine in my view. I'd look hard at Rust if I was interested in that, since that could relatively easily support Python bindings; or maybe C++.

**Comment by ishandutta2007** [comment]
@scanny Thanks for clarifying why it is outside the scope of this library. 

To give you some context of where I am coming from, my task at hand requires me to accomplish an end to end video generation via code after generating a pptx. I am stuck at the last stage as I have to manually open up a power point application to export the generated ppt slideshow as a video. 
I am not too concerned about language or library to accomplish it, so if you know of any means to export the slideshow as a video programatically (irrespective of library and language) do let me know. Meanwhile I will explore options in Rust as you suggested. Asking AI chatbot for suggestions give something like this in C# (I am not sure it is correct though)
```
    Application application = new Microsoft.Office.Interop.PowerPoint.Application();
    Presentation ppt = application.Presentations.Open("myppt.pptx", MsoTriState.msoFalse, MsoTriState.msoFalse, MsoTriState.msoFalse);
    
    ppt.CreateVideo("myppt.mp4");

```

possibly from here : https://stackoverflow.com/q/71842426

**Comment by MartinPacker** [comment]
I have to ask: Why are you going via ppt? And not pptx?  ppt eliminates python-pptx; pptx doesn't.

I also have to ask what platform you're doing this on. On Mac, at least, there might be additional automation capabilities. This might get to 90% automated rather than 100% - and you might still count that as an "automation win".

**Comment by ishandutta2007** [comment]
@MartinPacker 
Sorry I meant pptx only.
Yes I can do it on Mac if needed. Can you elaborate the option on Mac that you briefly alluded to.

**Comment by MartinPacker** [comment]
Well, maybe AppleScript can do it.

**Comment by scanny** [comment]
@ishandutta2007 the C# code you posted looks plausible. I expect that's a reliable way to do the job if you can run on Windows. Pretty sure that `Microsoft.Office.Interop.PowerPoint.Application()` bit is going to fire up the actual `PowerPoint` application on the machine, roughly the way VBA does (or did at least). It will be single-threaded and slow (comparatively), but should be able to do anything that you can do by hand. It's a perfectly legitimate way to do PowerPoint operations, just won't run on Linux and not suitable for server-side operations in most cases.

If I had to do the job you mention, scale was low, and Windows was an option, I would probably choose that approach, although I would probably use VBA to avoid the C# toolchain and learning curve since the code is so simple.

**Comment by scanny** [comment]
Btw I've tried the AppleScript approach before and found it very frustrating, perhaps mostly because I couldn't find any decent documentation at the time. That would probably be my last-ditch approach.

**Comment by MartinPacker** [comment]
I don't disagree on AppleScript; Microsoft's dictionaries are a little obtuse. (My experience is mostly with Excel.)

I hope I successfully deployed the subjunctive mood. 😀
