### ISSUE TITLE
Issue with creating a single category ChartData 

### ISSUE THREAD

**Issue by EdricLiu7788** [scanny/python-pptx#428]
Hi there,

I'm having trouble creating the ChartData with single category, here is my code:

chartdata1.categories = [function_dict['function_3']]
chartdata1.add_series(type_serise['1'], (type_1[6]), '0%')
chartdata1.add_series(type_serise['2'], (type_2[6]), '0%')

The Error is:
TypeError: 'float' object is not iterable

The code works well with 2+ categories:

chartdata1.categories = [function_dict['function_2'], function_dict['function_3']]
chartdata1.add_series(type_serise['1'], (type_1[5], type_1[6]), '0%')
chartdata1.add_series(type_serise['2'], (type_2[6], type_2[6]), '0%')

Much appreciated for your help!
Edric

BTW, could you please let me know if there will have the 'Delete slide' function release?

**Comment by EdricLiu7788** [comment]
Follow-ups: I also tried to replace the list/dictionary with actual numbers, but still get with the same error:

File "C:\Users\Edric\AppData\Roaming\Python\Python37\site-packages\pptx\chart\data.py", line 294, in add_series
    for value in values:
TypeError: 'float' object is not iterable

And my goal is to build a bar chart with only one bar and multiple series:

![default](https://user-images.githubusercontent.com/42666446/44575099-c294f680-a7bd-11e8-97dc-a50726f445ec.PNG)

**Comment by scanny** [comment]
This line of Python code:

```python
chartdata1.add_series('Series 1', (42.0), '0%')
```

is the same as writing this:

```python
chartdata1.add_series('Series 1', 42.0, '0%')
```

Both of which are invalid calls to `.add_series()` because it's expecting
a sequence (e.g. list or tuple) as its second parameter.

A single-element tuple has a distinct "trailing-comma" syntax, so this is
what the tuple above should look like: `(42.0,)`.

Long story short, if you change your code to look like this:

```python
chartdata1.add_series(type_serise['1'], (type_1[6],), '0%')
```

Then it should avoid this error.

You could also use a list (e.g. `[type_1[6]]`) which doesn't have the same subtleties concerning commas.
