### ISSUE TITLE
x-axis values in a chart

### ISSUE THREAD

**Issue by akashsharma03** [scanny/python-pptx#433]
I am trying to retrieve chart data from a chart and store it in a dataframe. I am able to get all the series name and their values but I am not able to get the x-axis values. 
series name act as index, series values act as the values in the dataframe and x-axis values would act as the column names but I am not able to retrieve that.
Here's the snippet of code:

def getChartData(chart):
    series_names = []
    series_data = []

    for series in chart.series:
        series_names.append(series.name)
        series_data.append(series.values)

    chart_data = pd.DataFrame(series_data,index = series_names)

    return chart_data

**Comment by scanny** [comment]
I think you're looking for `chart_data.categories`:  
https://python-pptx.readthedocs.io/en/latest/api/chart-data.html#pptx.chart.data.CategoryChartData.categories

**Comment by akashsharma03** [comment]
Hi Steve,
Thanks I looked into this.
But I am not able to get the values from an existing chart. 
can you please attach a snippet of code that can help me.

P.s: the chart object in the function is a pptx.chart.chart.Chart object. 

Thanks in advance

**Comment by scanny** [comment]
Something like this might work:

```python
categories = chart.plots[0].categories
```

**Comment by akashsharma03** [comment]
Thanks a lot Steve.
It Worked :+1:

**Comment by akashsharma03** [comment]
Also, is there any way to figure out if this chart object is plotby row/columns?
Meaning if the series are in columns or row

**Comment by alicegreene988** [comment]
Hi Steve, 
I'm trying to plot an area chart using pptx but somehow my x-axis keeps getting displayed as a category axis instead of date-axis even though chart_data.categories.are_numeric returns True. How can I convert the category axis into a date axis?
Attached CategoryAxis.JPG is what my plot currently looks like, DateAxis is what I want it to look like. Thanks in advance.
![dateaxis](https://user-images.githubusercontent.com/46582049/51006182-b52b9f00-1507-11e9-9c03-3796fbfa5a81.JPG)
![categoryaxis](https://user-images.githubusercontent.com/46582049/51006184-b6f56280-1507-11e9-9fdf-2c38d6e73000.JPG)

**Comment by scanny** [comment]
@alicegreene988 I believe if you convert the category values to Python `date` or `datetime` before adding them to the chart-data object you'll get a date axis for the category axis.

**Comment by alicegreene988** [comment]
Thank you for the prompt response. Unfortunately my category data are not actual dates, they are numbers ranging from 0 to 1000 as shown above. I'm trying to convert from a category axis to a date axis because when I do that manually in Power Point, the x-axis scales properly, otherwise the category data is treated as text.

When I force chart_data.categories = pd.to_datetime(df_area_chart['Index']) the chart fails to plot. 
![image](https://user-images.githubusercontent.com/46582049/51041058-a59b6d00-157e-11e9-9237-e682cdeae62e.png)
