### ISSUE TITLE
How do i create a macro in python-pptx

### ISSUE THREAD

**Issue by mackinleyhills** [scanny/python-pptx#484]

**Comment by MartinPacker** [comment]
I know @scanny closed this just now - and I'm not seeking to undo that - but I thought I'd make a useful comment:

I looked at this recently and there's what I take to be an unsurmountable roadblock for **anybody** manipulating .pptx or (more accurately) .pptm files: The macro itself is stored **compiled**.

It is entirely feasible to have a shape whose click action is to run a macro - because the link is in text format.

(I might well do this latter in my md2pptx project.)

So, I can see why it's right for @scanny to close this.
