### ISSUE TITLE
picture crop_top changes aspect ratio of picture

### ISSUE THREAD

**Issue by christinahaig** [scanny/python-pptx#509]
I'm not certain if all crop_x methods do this, however when I add a png picture using the add_picture method, and then do crop_top on the shape, the image gets stretched to fit the original shape instead of the shape getting resized so the picture stays the same aspect ratio.  Is this a feature or bug?  Can it be changed?

**Comment by scanny** [comment]
This is the expected behavior. If you want to avoid stretching, you'll need to size the picture shape to the post-cropping proportions, either before `.add_picture()` or after. As you'll see when doing this, there are other questions to be answered, like if you crop the top, do you want the bottom to stay where it is or the top-left corner to stay where it is (default behavior) or do you want the "center" to be the anchor. So `python-pptx` would have to do a lot of guessing in order to be "helpful" for this, which we avoid because it never actually ends up being helpful.

The other thing you can do is "hard" crop your pictures ahead of time, like with Pillow or something, and then insert the pre-cropped images.
