### ISSUE TITLE
Cannot find definition of XL_ORIENTATION

### ISSUE THREAD

**Issue by Wolfever** [scanny/python-pptx#549]
I was trying to change the direction of axis title, and I found the following analysis:
[Axis Title](https://python-pptx.readthedocs.io/en/latest/dev/analysis/cht-axis-title.html)

However, while I was following the directions, I couldn't find the definition of XL_ORIENTATION under pptx.enum.chart. Is it because I looked in the wrong directory? If not, what should be the definition?

**Comment by scanny** [comment]
The page you linked to is a "pre-development" analysis page, so it specs out the work that _needs_ to be done rather than documenting work that _has been_ done.

So the simple answer is that enumeration doesn't exist yet. Which is probably not a terrifically big deal since there is no `AxisTitle.orientation` property to use it on.

As far as the definition should be, it depends on how you're going to use it. The XML just uses a `str` value in an attribute, so maybe you just need the right literals. But if you were going to build in the `oxml` layer for this property you probably want an `XmlEnumeration` object in the `pptx.enum.chart` module.

**Comment by Wolfever** [comment]
Thanks for your reply. I did some digging into the xml of axis title formatting but I am still unsure how to format the chart using python. 

The axis title part look like the following (I assume): 

`<c:title>
	<c:tx>
		<c:rich>
			<a:bodyPr rot="0" vert="wordArtVertRtl"/>
			<a:lstStyle/>
				<a:p>
					<a:pPr>
						<a:defRPr sz="1000"/>
					</a:pPr>
					<a:r>
						<a:rPr lang="zh-CN" altLang="en-US"/>
						<a:t>百分比</a:t>
					</a:r>
				</a:p>
		</c:rich>
	</c:tx>
	<c:overlay val="0"/>
</c:title>`

After experimenting a bit, I found that the default action of adding an axis title is to add a simple `<a:bodyPr/>` tag. However, I would like to change it to `<a:bodyPr rot="0" vert="wordArtVertRtl"/>` as it looks better with Chinese characters. 

Is there a quick way to do this? Thanks a lot!
