### ISSUE TITLE
Can not find MSO_SHAPE

### ISSUE THREAD

**Issue by cczls1991** [scanny/python-pptx#550]
When using "from pptx.enum.shapes import MSO_SHAPE"
Can not find MSO_SHAPE

**Comment by ulziibuyan** [comment]
Do you mean `from pptx.enum.shapes import MSO_SHAPE_TYPE` ?

**Comment by cczls1991** [comment]
According to the example：

>   from pptx.enum.shapes import MSO_SHAPE
>         from pptx.util import Inches
>         left = top = width = height = Inches(1.0)
>         slide.shapes.add_shape(
>             MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height
>         )

The error shows that “can not find reference “MSO_SHAPE” in shapes.py ”

Version：0.6.18
IDE: PyCharm

**Comment by scanny** [comment]
This is a PyCharm warning only. The code should execute fine. The problem is that `MSO_SHAPE` is an "alias" of `MSO_AUTO_SHAPE_TYPE` that is defined on the enum instance, not the class. So PyCharm can't find it at compile time (it's not available until runtime).

To avoid the PyCharm message, use this instead:

```python
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.util import Inches

left = top = width = height = Inches(1.0)
slide.shapes.add_shape(
    MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE,
    left,
    top,
    width,
    height,
)
```

**Comment by cczls1991** [comment]
Got it！Many thanks！
