### ISSUE TITLE
I would like to be able to convert a textfile with markdown syntax to slides

### ISSUE THREAD

**Issue by tooh** [scanny/python-pptx#56]
### USER STORY

I would like to be able to convert a textfile with markdown syntax to slides
### DESCRIPTION

Markdown headers and bullet points should be translated to slides and bullets as follows:
- H1 text should become a Title slide
- H2 text should become the title of a Content slide
- H3,4,5,6 and bullet points should become bullet points in the content slide

All other text should be added to the slide notes

**Comment by myint** [comment]
I started working on [`rst2pptx`](https://github.com/myint/rst2pptx) for occasions where I must output PowerPoint instead of my usual reStructuredText/LaTeX/PDF route. So far it just handles simple slides that don't mix bullets/text with images. (I want to see if I'll actually use this tool much before I start looking into how to handle more complex slides.)

Thanks for `python-pptx` by the way!
