### ISSUE TITLE
 How to set the slides to 16:9

### ISSUE THREAD

**Issue by jackadam1981** [scanny/python-pptx#565]
How to set the slides to 16:9
The default is 4:3

**Comment by ferhat00** [comment]
Any progress on this?

**Comment by scanny** [comment]
Easiest way is to start with a "template" presentation having the proportions you prefer. This lets you set a lot of other options as well like custom masters, theme colors, etc.

Otherwise you can use `Presentation.slide_height` and `Presentation.slide_width` to set the slide dimensions you like:
https://python-pptx.readthedocs.io/en/latest/api/presentation.html#pptx.presentation.Presentation.slide_height
