### ISSUE TITLE
Can`t get access to real size property of text frame

### ISSUE THREAD

**Issue by ega3001** [scanny/python-pptx#588]
Hello!
I am trying to get font size of some text frames.
```
def _getFont(self, shape):
        font = shape.text_frame.paragraphs[0].runs[0].font
        if font.size == None:
            font = shape.text_frame.paragraphs[0].font
        return font
```
But every time i get None. Only when i set manually (in editor) same font on each shape object then i can get actual font object, but in my case i can not do it every time, i need to get them from source presentation, how  you and others get it?
Attached file for example of my problem
[people_content_ver_1.pptx](https://github.com/scanny/python-pptx/files/4108173/people_content_ver_1.pptx)

UPDATE: found that shapes has property like default size, that represents max size of the font when it needs to be viewed (in editor) and they upscale/downscale their font size to max when i change size of the shape. At least I think it happened ;)

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-pptx" tag.

What you're seeing is the expected behavior. The `Font` object only reports explicitly-set values. Most of the time, default settings from higher up the style hierarchy determine the effective settings for attributes like font size, color, typeface, etc. There is currently no API support for getting the "effective" settings for these attributes.
