### ISSUE TITLE
How to replace picture inserted in placeholder?

### ISSUE THREAD

**Issue by pei-lun** [scanny/python-pptx#598]
Hi. Can I replace the picture of `placeholder_picture` in the following code?

```python
from pptx import Presentation

prs = Presentation('presentation.pptx')
placeholder_picture = prs.slides[1].shapes[0]
print(type(placeholder_picture))  # <class 'pptx.shapes.placeholder.PlaceholderPicture'>
```

**Comment by veeshy** [comment]
`placeholder_picture.insert_picture('path/to/pic')`

**Comment by pei-lun** [comment]
@veeshy It will raise `AttributeError: 'PlaceholderPicture' object has no attribute 'insert_picture'`.

**Comment by scanny** [comment]
There's no API support for that unfortunately. Inserting a picture into a picture-placeholder changes the underlying element from a `<p:sp>` element to a `<p:pic>` element with quite a bit more content. We didn't implement the "reversal" operation for this one just because it was going to be a fair amount of work and it wasn't needed at the time.

**Comment by pei-lun** [comment]
So it seems I have to create a new slide with the picture placeholder and then insert new picture into it. Thanks for answering.
