### ISSUE TITLE
I would like to be able to include a standard footer in the slides

### ISSUE THREAD

**Issue by tooh** [scanny/python-pptx#64]
Footer should contain : 
- date of creation of the pptx
- standard footer text : like company name
- slide nr

All like in Powerpoint.

Powerpoint seems to handle this only if you have slides in the pptx.

I'm using an empty base pptx as template, so I do not get this footer in the generated pptx.

What is the best practice for this ?

**Comment by melosfox** [comment]
I'm dredging up this topic again because I haven't found anything more recent.

Our company uses footers for sources, special notes, etc. We have page numbers and copyright information as separate fields. This seems to be a specialized use for this, but the footer field is necessary to allow us to easily switch our slides to multiple aspect ratios (Footers in one aspect ratio will adjust to the new ratio correctly—this doesn't happen reliably with other text placeholders)

If I could activate the footer field and insert copy pertaining to each page, that would be ideal, since copy is unique to each page.

**Comment by scanny** [comment]
So it looks like PowerPoint doesn't create a footer placeholder on a slide during the normal create-slide-from-a-slide-layout operation; you have to use the View > Headers and Footers dialog to cause a footer placeholder to be added.

`python-pptx` mimics that behavior, but lacks the API support for later adding any of those "latent" placeholders.

If you are, or are willing to, run a private fork, you can modify this line to change that behavior for footer placeholders:  
https://github.com/scanny/python-pptx/blob/master/pptx/slide.py#L327

Just remove `PP_PLACEHOLDER.FOOTER` from that tuple and any footer placeholder on the slide layout should be "cloned" along with the others when creating a new slide with that layout.

Another possible approach would be something like this after the fact (and without need for maintaining a fork):

```python
footer_layout_placeholder = slide_layout.placeholders.get(12)
# ---12 is an example, use actual shape-id of footer placeholder on your slide layout
slide.shapes.clone_placeholder(footer_layout_placeholder)
footer_placeholder = slide.shapes.placeholders.get(42)  # or whatever shape-id is assigned
# or possibly this would work since it was added last
footer_placeholder = slide.shapes[-1]
```

**Comment by MartinPacker** [comment]
Counterpoint on adding it to the slide master

I'm generating my presentations from a template one. I generally create 5 - 10 per customer engagement. I'm being asked to add a footer with the customer's name (bottom left).

I don't really want to create a new template pptx (actually pptm but nevermind) for each customer engagement; I want to add the left footer text programmatically.

I'll continue to research but might have to try to add it via VBA - as I always run some VBA macros to convert from pptm to pptx and do some other things prior to "publication:.
