### ISSUE TITLE
Feature request: Include placeholders for footer, page number, and date

### ISSUE THREAD

**Issue by daniel-raimi-zlatic** [scanny/python-pptx#658]
I have read the documentation for creating slides from placeholders here:

https://python-pptx.readthedocs.io/en/latest/dev/analysis/placeholders/slide-placeholders/placeholders-in-new-slide.html

It seems that the placeholders for footer, page number, and date do not get added into a slide. However, I definitely do want those placeholders to be added. Is this possible?

**Comment by Melendowski** [comment]
Not to speak for Scanny here but he seems to follow very closely to how Microsoft does it. This is probably because of how the OXML standard dictates it. If you were create slide layouts and have footer/page number/date turn on within the slide master, and then applied those layouts to new slides in the presentation, the footer/page number/date would not be available as shapes you can access. 

This is exactly how the process would go if you were to use win32com interoperability server instead of python-pptx. You can verify this quite easily. Open a pptx file in Powerpoint, apply a slide with a specific layout and go to `Home -> Editing -> Select -> Selection Pane` and now go to `View->Slide Master`. You can see for the given layout that the the footer/page number/date in the slide master but not on the presentation slide. 

Just how it is, sorry.

**Comment by scanny** [comment]
In PowerPoint, there are distinct operations to add these placeholders to a slide; you can see icons for these in the toolbar:
![image](https://user-images.githubusercontent.com/2062718/97028884-8ed6c800-1511-11eb-8d7e-f2caf3fb5633.png)

I believe the placeholders in the slide-master determine where these are positioned and their size and formatting when and if they are added to a slide by clicking one of these buttons, but they are not added to all slides by default. I expect PowerPoint has some way of adding these to a selected group of slides in one operation.

In any case, that particular operation has no API support in `python-pptx`.
