### ISSUE TITLE
Enhancement: equality of slides across files

### ISSUE THREAD

**Issue by toyg** [scanny/python-pptx#659]
At the moment, there doesn't seem to be an easy way of checking for equality of slides (or, I guess, any object) across different files. This is the current behavior:

```python
# file1_copy is an identical duplicate of file1
>>> p1 = Presentation('file1.pptx')
>>> p2 = Presentation('file1_copy.pptx')
# ideally this check should return True
>>> p1.slides[0] == p2.slides[0]
False
```

The current `__eq__` implementation seems to pay attention to the actual source of proxied XML elements, but I guess it doesn't do it across separate XML trees.

**Comment by scanny** [comment]
In this case, the following expression should work:

```python
p1.slides[0]._element.xml == p2.slides[0]._element.xml
```

Seems like a very narrow case though. This requirement is pretty narrow (not often called for) to begin with, but then there are a number of "shades" of equality I can think of. This one is actual literal equality of expression, but what about the same shapes in a different z-order? That would be visually equivalent. And there can be other alternative ways ways to express a visually identical slide, like grouping differences or optional attributes that express the same thing as the default (omitted) attribute.

The existing `slide == other_slide` behavior is important because there can be more than one `Slide` object referring to the same slide in the underlying XML. A `Slide` object is just a proxy to the underlying XML and this "points to the same underlying XML slide" behavior comes up as important to know in several places.

So you get the idea. This would be far along on the long tail of infrequently needed features and actually identifies a family of features, each of which is even further down the tail.

I expect the best course for someone needing this would be to implement it themselves according to their particular requirements, unless the literal equality does the trick.
