### ISSUE TITLE
Any way to remove resource file?

### ISSUE THREAD

**Issue by senayuki** [scanny/python-pptx#670]
For example, I want to remove a huge image file which full-screen in a slide. So I remove the shape, then remove the slides.
However, the huge image still lay in ./ppt/media.
I tried to remove or edit the Image object from the Picture shape. But I don't know how to remove an Image object.

```python
shape._element.getparent().remove(shape._element)
slides = list(document.slides._sldIdLst)
document.slides._sldIdLst.remove(slides[page-1])
```

Now, how can I remove this file?

**Comment by scanny** [comment]
You need to remove the relationship, because that is what is traversed in the process of saving.

A relationship is between one "part" and another. In this case, between the Slide part and an Image part.

* You get the slide part from the slide with something like: `slide._part` -> SlidePart.
* You remove the relationship with something like: `slide_part.drop_rel(rId)`
* You get the relationship-id (`rId`) from the original picture shape with something like: `picture._pic.blip_rId`.

The image part is only removed (upon saving) if there are no relationships to it. So if it is used more than once, you have to remove all those picture-shapes and their image relationships.
