### ISSUE TITLE
changing the filename(partname) in pptx

### ISSUE THREAD

**Issue by NarenZen** [scanny/python-pptx#686]
@scanny How to change the filename(partname) of files present in **/ppt/slideMasters/** or **/ppt/slideMasters/** etc... in python-pptx itself

For example, in **/ppt/slideMasters/** there is a file called **slideMaster1.xml** named by default naming convention.
How/ Where to change this file name to **slideMaster_Mine.xml** in python-pptx itself while saving the presentation using `prs.save('test.pptx')`

**Comment by Melendowski** [comment]
@NarenZen Bottom line, you can't change that. Then all the built oxml relationships pointing towards **slideMaster1.xml** would need to be updated.

**Comment by scanny** [comment]
The question in my mind is "Why might someone want to do that?".

These names are arbitrary, and I've seen packages with very different names, so there's no magic about `slide1.xml` except that's how PowerPoint does it and a convention for this sort of thing is useful.

There's no way to change those names from the PowerPoint UI or even from the MS API as far as I know, and I can't think of any good reason why one would want to change those. They are a concern of the packaging code which is pretty low level and just doesn't come into things when you're navigating a package because you're traversing relationships that explicitly state the part names.

I'd be interested to hear why you think this would be a good idea, but I'm pretty sure you're going to be on your own for this. It would be fairly easy to modify a PPTX package to rename the parts, just rename the package parts (Zip archive "files") to suit and then traverse all the .rels files to change the relationship partnames to match.

Closing this, but @NarenZen would still like to hear about your use case if you have one in mind.

**Comment by NarenZen** [comment]
@scanny Exactly did the steps what you said to rename the files.

Reason for doing this is to merge multiple pptx files.

While merging multiple pptx files, if there are two different files in two different pptx files  (eg: image1.png) , while merging two pptx files, the file (image1.png) are getting replaced by diiferent file but with same name (image1.png) which is present in second pptx file.

Anyways sorted out by myself, Thanks

**Comment by lqq357** [comment]
Using java with ‘spire.presentation.free.jar’ can solve your problem. 
like this demo.
![Uploading aaa.png…]()

**Comment by lqq357** [comment]
![aaa](https://user-images.githubusercontent.com/44636391/127730035-2346c10a-3955-4f6e-887b-0923b5134719.png)
