### ISSUE TITLE
fit_text() doesn't work if the TextFrame is in a cell

### ISSUE THREAD

**Issue by XZETGEXI** [scanny/python-pptx#701]
`table_shape = slide.shapes.add_table(*table_dimensions)`
`table = table_shape.table`
`table.cell(0,0).text = "Lorem Ipsum"`
`table.cell(0,0).text_frame.fit_text()`

gives the following error:

`AttributeError: '_Cell' object has no attribute 'width'`

It seems the `TextFitter` object calls the parent of the `TextFrame`, which is `Cell`, which triggers the bug.

Allowing to override `font_size` in `fit_text` would be a quick fix.

**Comment by MartinPacker** [comment]
When I've worked with tables I've been able to resize the **columns** rather than individual cells. And their height is going to take into account the largest height requirement of all the cells in the row.

**Comment by scanny** [comment]
Yeah, `.fit_text()` is experimental, was only intended for shapes, and was really a best-effort hack from the start. It's not going to work on a table cell anyway because cell widths are not independent, i.e. setting the width of one cell is not going to set the width of the table column.

So I'm afraid you're on your own with this one. The official response is "don't call `text_frame.fit_text()` on a table cell".
