### ISSUE TITLE
PicturePlaceholder and insert_picture

### ISSUE THREAD

**Issue by darsh97** [scanny/python-pptx#736]
Hi everyone, I have a requirement where I need to compare slides from ppt's.

**`_<pptx.shapes.placeholder.PlaceholderPicture object at 0x0000018E5E1123D0>_`** dosen't seem have a insert_picture method to it.

The placeholder format type is **`PICTURE (18)`** but its still missing the method.

```
AttributeError: 'PlaceholderPicture' object has no attribute 'insert_picture'
```
or am I missing something trivial?

Thank you.

**Comment by MartinPacker** [comment]
That's because it's `add_picture()`. Not to get at you but this seems to keep coming up on Stack Overflow as well. I'm wondering why.

**Comment by darsh97** [comment]
That did it. Thank you.

**Comment by scanny** [comment]
@MartinPacker I don't think that's quite right. A `PicturePlaceholder` object does indeed have an `.insert_picture()` method. It's just that it can only be called once (roughly).

A `PicturePlaceholder` object is an "empty" placeholder that can only accept a picture. When you call `.insert_picture()` on that object, it becomes a `PlaceholderPicture` object; basically a "populated" picture-placeholder.

Under the covers, a `PicturePlaceholder` is a `<p:sp>` (sp=>shape) object, like a rectangle. A `PlaceholderPicture` is a `<p:pic>` element, which makes sense because it now contains a picture and is not just a rectangle anymore.

It might be cool to have a `.replace_picture()` method or something like that, but that doesn't exist yet and I'm not sure it's available in the Microsoft API either. In the application, if you select the picture and delete it, I believe it reverts back to the `PicturePlaceholder` object it was originally.

**Comment by MartinPacker** [comment]
Ah. Thank you @scanny. I think that probably explains why we get so many questions about this.
