### ISSUE TITLE
Adding picture with & character (ampersand) to pptx 

### ISSUE THREAD

**Issue by manuelpetra27** [scanny/python-pptx#747]
Hi Scanny, 

I have a query about adding picture with '&' character to pptx, seems been asked in #223 and #718 but I don't really understand the solution. When I add picture, it always gives me an error like this:

XMLSyntaxError: xmlParseEntityRef: no name, line 3, column 70

I tried to change the '&' to '&amp;' on the picture's filename but didnt work.  Do you have any advice for this?
Fyi, the pic was taken from a URL, so I replaced the '&' char and change it to UTF-8 encoding char '%26' before switched back again to '&' when I used the urllib.request.urlretrieve command.

Thank you very much
Regards,
Petra

**Comment by scanny** [comment]
This was fixed in the latest release. If you upgrade with `pip install -U python-pptx` that should do the trick. There's no way short of monkey-patching to fix it otherwise that I can see, other than renaming the file to remove the ampersand, because the filename is derived from the path passed as a parameter in the call.

**Comment by manuelpetra27** [comment]
It works now,

Thanks Scanny !
